---
- name: Crear usuario nuevo
  hosts: all
  gather_facts: false
  tasks:
    - name: Tarea de crear usuario
      user: keniap
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        groups: "{{ admin_group }}"
      loop:
        - usuario1
        - usuario2
        - usuario3
        - usuario4
...